name: 'Deploy'

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    environment:
      name: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - run: SECRET="${{ secrets.SECRET_TEST }}" echo "${SECRET}"
