name: 'Deploy'
on:
  workflow_dispatch: {}
jobs:
  deploy:
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: >
          if [[ "${DUMMY_SECRET}" == "dummy" ]]; then
            echo "dummy"
          else
            echo "not dummy"
          fi
        env:
          DUMMY_SECRET: ${{ secrets.DUMMY_SECRET }}
